### ISSUE TITLE
human readable demurrage rate

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#4]
currently, the demurrage rate is hard-coded for all currencies:

https://github.com/encointer/pallets/blob/f60169a908675bb90ae54cfa8b9000fc08ca45e7/currencies/src/lib.rs#L156

The explorer shows the demurrage rate as: 911009525721700500 which is the read value times blocks per month.

Read value:
```matlab
hex2dec("1E3F0A8A973")
ans =    2.0785e+12
```
which represents a `I64F64` fixpoint value. 

Human readable would be percent per month:
```matlab
octave:23> blockspermonth = 86400/6*356/12;
octave:24> dr = hex2dec("1E3F0A8A973")/2^64
dr =    1.1268e-07
octave:26> exp(-dr * blockspermonth)
ans =  0.95300
octave:27> (1-exp(-dr * blockspermonth))*100
ans =  4.6995
```
That's what should be displayed (with three significant digits): *4.70%/month*

**Comment by demyanrogozhin** [comment]
Thats because polkadot-js doesn'l support fixed point numbers, and demurrage sent  as I128, which currently converted with .toNumber() method.
To fix this fixed point to Number conversion method [parseFixPoint](https://github.com/encointer/explorer/blob/140a8753569c4abf7d6513cf6b217002f743e4b8/src/utils.js#L4) should be rewritten, to support different word sizes

**Comment by brenzi** [comment]
agreed. now all is clear
